plugins {
    id 'java'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

apply plugin: "xyz.wagyourtail.unimined"

base {
    archivesName = project.archives_base_name
}

version = project.mod_version
group = project.maven_group

java {
    sourceCompatibility = JavaVersion.toVersion(25)
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'spongepowered-repo'
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "JitPack"
        url = "https://jitpack.io"
    }
    maven {
        name = 'babbaj-repo'
        url = 'https://babbaj.github.io/maven/'
    }
    flatDir {
        dirs 'baritone-26.3/fabric/build/libs', 'baritone-26.3/dist', 'libs'
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.7"
    compileOnly "org.ow2.asm:asm:9.7"

    implementation 'com.fasterxml.jackson.core:jackson-core:2.16.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.16.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.0'
    shadow 'com.fasterxml.jackson.core:jackson-core:2.16.0'
    shadow 'com.fasterxml.jackson.core:jackson-annotations:2.16.0'
    shadow 'com.fasterxml.jackson.core:jackson-databind:2.16.0'

    implementation 'dev.babbaj:nether-pathfinder:1.6'
    shadow 'dev.babbaj:nether-pathfinder:1.6'

    compileOnly files('baritone-26.3/fabric/build/libs/baritone-fabric-26.3-SNAPSHOT-dev-shadow.jar')
}

unimined.minecraft(sourceSets.main, true) {
    version "26.3"

    mappings {
        mojmap()
    }
}

unimined.minecraft {
    fabric {
        loader "0.19.5"
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
            include 'adris/altoclef/AltoClef.java'
            include 'adris/altoclef/AltoClefCommands.java'
            include 'adris/altoclef/Debug.java'
            include 'adris/altoclef/Settings.java'
            include 'adris/altoclef/commandsystem/ArgParser.java'
            include 'adris/altoclef/commandsystem/Command.java'
            include 'adris/altoclef/commandsystem/CommandExecutor.java'
            include 'adris/altoclef/commandsystem/StringReader.java'
            include 'adris/altoclef/commandsystem/TabCompleter.java'
            include 'adris/altoclef/commandsystem/args/Arg.java'
            include 'adris/altoclef/commandsystem/args/DoubleArg.java'
            include 'adris/altoclef/commandsystem/args/EnumArg.java'
            include 'adris/altoclef/commandsystem/args/FloatArg.java'
            include 'adris/altoclef/commandsystem/args/IntArg.java'
            include 'adris/altoclef/commandsystem/args/ListArg.java'
            include 'adris/altoclef/commandsystem/args/StringArg.java'
            include 'adris/altoclef/commandsystem/exception/**'
            include 'adris/altoclef/commands/HelpCommand.java'
            include 'adris/altoclef/commands/LegitMovementCommand.java'
            include 'adris/altoclef/commands/StopCommand.java'
            include 'adris/altoclef/commands/ReloadSettingsCommand.java'
            include 'adris/altoclef/commands/StatusCommand.java'
            include 'adris/altoclef/commands/CoordsCommand.java'
            include 'adris/altoclef/commands/GamerCommand.java'
            include 'adris/altoclef/commands/GetCommand.java'
            include 'adris/altoclef/commands/GotoCommand.java'
            include 'adris/altoclef/commands/PauseCommand.java'
            include 'adris/altoclef/commands/UnPauseCommand.java'
            include 'adris/altoclef/commands/TestCommand.java'
            include 'adris/altoclef/eventbus/EventBus.java'
            include 'adris/altoclef/eventbus/Subscription.java'
            include 'adris/altoclef/eventbus/events/SendChatEvent.java'
            include 'adris/altoclef/eventbus/events/TitleScreenEntryEvent.java'
            include 'adris/altoclef/eventbus/events/ClientTickEvent.java'
            include 'adris/altoclef/eventbus/events/ClientRenderEvent.java'
            include 'adris/altoclef/eventbus/events/TaskFinishedEvent.java'
            include 'adris/altoclef/mixins/ChatInputMixin.java'
            include 'adris/altoclef/mixins/EntryMixin.java'
            include 'adris/altoclef/mixins/ClientTickMixin.java'
            include 'adris/altoclef/mixins/ClientUIMixin.java'
            include 'adris/altoclef/ui/CommandStatusOverlay.java'
            include 'adris/altoclef/ui/MessagePriority.java'
            include 'adris/altoclef/tasksystem/Task.java'
            include 'adris/altoclef/tasksystem/TaskChain.java'
            include 'adris/altoclef/tasksystem/TaskRunner.java'
            include 'adris/altoclef/tasksystem/ITaskCanForce.java'
            include 'adris/altoclef/chains/TaskChain.java'
            include 'adris/altoclef/chains/SingleTaskChain.java'
            include 'adris/altoclef/chains/UserTaskChain.java'
            include 'adris/altoclef/chains/MobDefenseChain.java'
            include 'adris/altoclef/chains/FoodChain.java'
            include 'adris/altoclef/chains/MLGBucketFallChain.java'
            include 'adris/altoclef/chains/DeathMenuChain.java'
            include 'adris/altoclef/util/time/Stopwatch.java'
            include 'adris/altoclef/tasks/construction/MineBlockTask.java'
            include 'adris/altoclef/tasks/resources/GetItemTask.java'
            include 'adris/altoclef/tasks/movement/GotoTask.java'
            include 'adris/altoclef/tasks/speedrun/BeatMinecraftTask.java'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 25
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier.set "dev-shadow"
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set null
}

jar {
    archiveClassifier.set "dev"
}
