plugins {
    id 'fabric-loom' version '1.7.3'
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

archivesBaseName = "altoclef"
version = "1.21.1-0.20-legit"
group = "adris.altoclef"

repositories {
    mavenCentral()
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "MiranCZRepo"
        url = "https://mirancz.github.io/maven/"
        artifactUrls("https://mirancz.github.io/maven/cabaletta/baritone-unoptimized/1.21.1")
    }
    maven {
        name = 'babbaj-repo'
        url = 'https://babbaj.github.io/maven/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings "net.fabricmc:yarn:1.21.1+build.3:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.2"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.3.5")))
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.110.0+1.21.1"

    implementation 'com.fasterxml.jackson.core:jackson-core:2.16.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.16.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.0'
    shadow 'com.fasterxml.jackson.core:jackson-core:2.16.0'
    shadow 'com.fasterxml.jackson.core:jackson-annotations:2.16.0'
    shadow 'com.fasterxml.jackson.core:jackson-databind:2.16.0'

    implementation 'dev.babbaj:nether-pathfinder:1.5'
    shadow 'dev.babbaj:nether-pathfinder:1.5'

    modImplementation "cabaletta:baritone-unoptimized-fabric:1.21.1"
    include "cabaletta:baritone-unoptimized-fabric:1.21.1"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = "UTF-8"
}

shadowJar {
    configurations = [project.configurations.shadow]
}

remapJar {
    dependsOn shadowJar
    inputFile.set(shadowJar.archiveFile)
}
