# Gradle performance improvements
org.gradle.jvmargs=-Xmx8192M
org.gradle.vfs.watch=true
kapt.use.worker.api=true
kapt.include.compile.classpath=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all

# Minecraft and Loader versions for 26.3
minecraft_version=26.3
loader_version=0.19.5
fabric_version=0.19.5

# Mod Properties
mod_version=26.3-0.21-legit
maven_group=adris.altoclef
archives_base_name=altoclef
