pluginManagement {
    repositories {
        mavenLocal()
        maven {
            name = 'WagYourMaven'
            url = 'https://maven.wagyourtail.xyz/snapshots'
        }
        maven {
            name = 'ForgeMaven'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'FabricMaven'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal() {
            content {
                excludeGroup "org.apache.logging.log4j"
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'altoclef'
