repositories {
    mavenLocal()
    maven {
        name = 'WagYourMaven'
        url = 'https://maven.wagyourtail.xyz/releases'
    }
    maven {
        name = 'WagYourMaven Snapshots'
        url = 'https://maven.wagyourtail.xyz/snapshots'
    }
    maven {
        name = 'ForgeMaven'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'FabricMaven'
        url = 'https://maven.fabricmc.net/'
    }
    mavenCentral()
}

dependencies {
    implementation group: 'xyz.wagyourtail.unimined', name: 'xyz.wagyourtail.unimined.gradle.plugin', version: '1.4.2-SNAPSHOT'
}
